# Generated by Django 2.1.3 on 2018-11-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
