# Generated by Django 2.1.3 on 2018-11-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='Enter your Products description', max_length=150)),
                ('price', models.DecimalField(decimal_places=2, default=135.0, max_digits=10)),
            ],
        ),
    ]
